# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kepler_name', models.CharField(max_length=100)),
                ('koi_name', models.CharField(max_length=100)),
                ('kepler_id', models.IntegerField()),
                ('planet_radius', models.FloatField()),
                ('surface_temp', models.IntegerField()),
                ('inclination', models.FloatField()),
                ('semimajor_axis', models.FloatField()),
                ('orbital_period', models.FloatField()),
                ('transits_observed', models.IntegerField()),
                ('ingress_duration', models.FloatField()),
                ('transit_duration', models.FloatField()),
                ('transit_depth', models.FloatField()),
                ('habitable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_designation', models.CharField(max_length=100)),
                ('right_ascension', models.FloatField()),
                ('declination', models.FloatField()),
                ('stellar_temp', models.IntegerField()),
                ('stellar_radius', models.FloatField()),
                ('stellar_mass', models.FloatField()),
                ('light_years_dist', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kepler_exoplanets.Star'),
        ),
    ]
