# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kepler_exoplanets', '0002_auto_20151215_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='kepler_exoplanets.Star'),
        ),
    ]
